### ISSUE TITLE
invalid sample file names lead to termination in build_report

### ISSUE THREAD

**Issue by rndm4000** [Acribbs/tRNAnalysis#14]
hi adam, 
i ran my own samples, whose filenames coincidentally start with numbers (got them this way from the sequencing). the pipeline itself ran ok, but in the build_report stage, i got an exception from R, `undefined columns selected`, due to `read.table()` adding an X in front of every colname.

i fixed it by setting `check.names = F`, but i don't know if this would be a desirable default.

kind regards,

sebastian

**Comment by Acribbs** [comment]
Thanks for making the issue, this is something I hate about R in general (especially since it doesn't give you any warnings).

I would prefer not to use `check.names = F` at the moment as I would like R to warn if there are duplicate names. I can add a section in the documentation stating that the names shouldn't be named with an int at the beginning.
